/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Midtract {
      
    export type OrderStruct = {buyer: AddressLike, seller: AddressLike, amount: BigNumberish, state: BigNumberish}

    export type OrderStructOutput = [buyer: string, seller: string, amount: bigint, state: bigint] & {buyer: string, seller: string, amount: bigint, state: bigint }
  
    }

  export interface MidtractInterface extends Interface {
    getFunction(nameOrSignature: "eip712Domain" | "getOrder" | "lockFunds" | "nonces" | "onboardWithPermit" | "orders" | "owner" | "poolWallet" | "refundFunds" | "relayer" | "releaseFunds" | "renounceOwnership" | "setPoolWallet" | "setRelayer" | "stablecoin" | "sweep" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EIP712DomainChanged" | "Locked" | "OwnershipTransferred" | "PoolWalletUpdated" | "Refunded" | "RelayerUpdated" | "Released" | "Swept"): EventFragment;

    encodeFunctionData(functionFragment: 'eip712Domain', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOrder', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'lockFunds', values: [BytesLike, AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'nonces', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'onboardWithPermit', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'orders', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'poolWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'refundFunds', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'relayer', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseFunds', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPoolWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setRelayer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'stablecoin', values?: undefined): string;
encodeFunctionData(functionFragment: 'sweep', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'eip712Domain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nonces', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onboardWithPermit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'poolWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'relayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPoolWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRelayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stablecoin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sweep', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace EIP712DomainChangedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LockedEvent {
      export type InputTuple = [orderId: BytesLike, buyer: AddressLike, seller: AddressLike, amount: BigNumberish];
      export type OutputTuple = [orderId: string, buyer: string, seller: string, amount: bigint];
      export interface OutputObject {orderId: string, buyer: string, seller: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PoolWalletUpdatedEvent {
      export type InputTuple = [newPoolWallet: AddressLike];
      export type OutputTuple = [newPoolWallet: string];
      export interface OutputObject {newPoolWallet: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundedEvent {
      export type InputTuple = [orderId: BytesLike, buyer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [orderId: string, buyer: string, amount: bigint];
      export interface OutputObject {orderId: string, buyer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RelayerUpdatedEvent {
      export type InputTuple = [newRelayer: AddressLike];
      export type OutputTuple = [newRelayer: string];
      export interface OutputObject {newRelayer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReleasedEvent {
      export type InputTuple = [orderId: BytesLike, seller: AddressLike, amount: BigNumberish];
      export type OutputTuple = [orderId: string, seller: string, amount: bigint];
      export interface OutputObject {orderId: string, seller: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SweptEvent {
      export type InputTuple = [from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, amount: bigint];
      export interface OutputObject {from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Midtract extends BaseContract {
    
    connect(runner?: ContractRunner | null): Midtract;
    waitForDeployment(): Promise<this>;

    interface: MidtractInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    eip712Domain: TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >
    

    
    getOrder: TypedContractMethod<
      [orderId: BytesLike, ],
      [Midtract.OrderStructOutput],
      'view'
    >
    

    
    lockFunds: TypedContractMethod<
      [orderId: BytesLike, buyer: AddressLike, seller: AddressLike, amount: BigNumberish, deadline: BigNumberish, signature: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    nonces: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    onboardWithPermit: TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, deadline: BigNumberish, v: BigNumberish, r: BytesLike, s: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    orders: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint] & {buyer: string, seller: string, amount: bigint, state: bigint }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    poolWallet: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    refundFunds: TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    relayer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    releaseFunds: TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setPoolWallet: TypedContractMethod<
      [_poolWallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setRelayer: TypedContractMethod<
      [_relayer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    stablecoin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    sweep: TypedContractMethod<
      [from: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'eip712Domain'): TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getOrder'): TypedContractMethod<
      [orderId: BytesLike, ],
      [Midtract.OrderStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'lockFunds'): TypedContractMethod<
      [orderId: BytesLike, buyer: AddressLike, seller: AddressLike, amount: BigNumberish, deadline: BigNumberish, signature: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nonces'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'onboardWithPermit'): TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, deadline: BigNumberish, v: BigNumberish, r: BytesLike, s: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'orders'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint] & {buyer: string, seller: string, amount: bigint, state: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'poolWallet'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'refundFunds'): TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'relayer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'releaseFunds'): TypedContractMethod<
      [orderId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPoolWallet'): TypedContractMethod<
      [_poolWallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRelayer'): TypedContractMethod<
      [_relayer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stablecoin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'sweep'): TypedContractMethod<
      [from: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EIP712DomainChanged'): TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
getEvent(key: 'Locked'): TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PoolWalletUpdated'): TypedContractEvent<PoolWalletUpdatedEvent.InputTuple, PoolWalletUpdatedEvent.OutputTuple, PoolWalletUpdatedEvent.OutputObject>;
getEvent(key: 'Refunded'): TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
getEvent(key: 'RelayerUpdated'): TypedContractEvent<RelayerUpdatedEvent.InputTuple, RelayerUpdatedEvent.OutputTuple, RelayerUpdatedEvent.OutputObject>;
getEvent(key: 'Released'): TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;
getEvent(key: 'Swept'): TypedContractEvent<SweptEvent.InputTuple, SweptEvent.OutputTuple, SweptEvent.OutputObject>;

    filters: {
      
      'EIP712DomainChanged()': TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
      EIP712DomainChanged: TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
    

      'Locked(bytes32,address,address,uint256)': TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
      Locked: TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PoolWalletUpdated(address)': TypedContractEvent<PoolWalletUpdatedEvent.InputTuple, PoolWalletUpdatedEvent.OutputTuple, PoolWalletUpdatedEvent.OutputObject>;
      PoolWalletUpdated: TypedContractEvent<PoolWalletUpdatedEvent.InputTuple, PoolWalletUpdatedEvent.OutputTuple, PoolWalletUpdatedEvent.OutputObject>;
    

      'Refunded(bytes32,address,uint256)': TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
      Refunded: TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
    

      'RelayerUpdated(address)': TypedContractEvent<RelayerUpdatedEvent.InputTuple, RelayerUpdatedEvent.OutputTuple, RelayerUpdatedEvent.OutputObject>;
      RelayerUpdated: TypedContractEvent<RelayerUpdatedEvent.InputTuple, RelayerUpdatedEvent.OutputTuple, RelayerUpdatedEvent.OutputObject>;
    

      'Released(bytes32,address,uint256)': TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;
      Released: TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;
    

      'Swept(address,uint256)': TypedContractEvent<SweptEvent.InputTuple, SweptEvent.OutputTuple, SweptEvent.OutputObject>;
      Swept: TypedContractEvent<SweptEvent.InputTuple, SweptEvent.OutputTuple, SweptEvent.OutputObject>;
    
    };
  }